development:
  requires_dark_launch: false

test:
  requires_dark_launch: false

staging:
  requires_dark_launch: false

acceptance:
  requires_dark_launch: false

vagrant:
  requires_dark_launch: false

production:
  requires_dark_launch: true