default: &default
  adapter: mysql2
  encoding: utf8
  pool: 25
  username: root
  password: 
  connect_timeout: 1
  read_timeout: 1
  write_timeout: 1
  checkout_timeout: 1

development:
  <<: *default
  database: stronghold_development

test:
  <<: *default
  database: stronghold_test

acceptance:
  <<: *default
  database: stronghold_acceptance

staging:
  <<: *default
  database: stronghold_staging
  password: root

production:
  <<: *default
  database: stronghold_production
  password: <%= ENV["DB_PASSWORD"] %>
