default: &default
  adapter: mysql2
  encoding: utf8
  pool: 25
  username: root
  password: 

development:
  <<: *default
  database: stronghold_development

test:
  <<: *default
  database: stronghold_test

acceptance:
  <<: *default
  database: stronghold_acceptance

staging:
  <<: *default
  database: stronghold_staging
  password: root

production:
  <<: *default
  host:     db0.datacentred.io
  port:     3306
  username: stronghold
  password: <%= ENV["DB_PASSWORD"] %>
  database: stronghold_production
