default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 

development:
  <<: *default
  database: stronghold_development

test:
  <<: *default
  database: stronghold_test

acceptance:
  <<: *default
  database: stronghold_acceptance

staging:
  <<: *default
  database: stronghold_staging
  password: root

production:
  <<: *default
  database: stronghold_production
  password: <%= ENV["DB_PASSWORD"] %>
