default: &default
  auth_url: "http://devstack.datacentred.io:5000/"
  openstack_client_image: '1cef2c7356c2'

development:
  <<: *default

test:
  <<: *default

acceptance:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  auth_url: "https://compute.datacentred.io:5000/"
