default: &default
  auth_url: "http://devstack.datacentred.io:5000/v3"
  openstack_client_image: 'datacentred/docker-openstack-client:alpine4'

development:
  <<: *default

test:
  <<: *default

acceptance:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  auth_url: "https://compute.datacentred.io:5000/v3"
