default: &default
  username: stronghold
  password: ''
  base_url: 'http://datacentred.atlassian.net'
  auth_path: '/rest/auth/1/session/'
  api_path: '/rest/api/latest/'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default