default: &default
  username: stronghold
  password: ''
  base_url: 'https://datacentred.atlassian.net/rest/api/2/'
  project: 'ST'
  user: 'issues'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default