default: &default
  auth_url: "http://devstack.datacentred.io:5000/v2.0/tokens"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  auth_url: "https://compute.datacentred.io:5000/v2.0/tokens"
