default: &default
  auth_url: "http://devstack.datacentred.io:5000/v2.0/tokens"
  identity_prefix: "/v2.0"

development:
  <<: *default

test:
  <<: *default

acceptance:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  auth_url: "https://compute.datacentred.io:5000/v2.0/tokens"
  # identity_prefix: "/v2.0"
