default: &default
  namespace: stronghold
  url: redis://localhost:6379/1

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

acceptance:
  <<: *default

production:
  <<: *default
  url: redis://queue.datacentred.io:6379/1
  network_timeout: 5
