# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  slack_webhook: <%= ENV["SLACK_WEBHOOK"] %>
  sirportly_token: <%= ENV["SIRPORTLY_API_TOKEN"] %>
  sirportly_secret: <%= ENV["SIRPORTLY_API_SECRET"] %>
  ceph_token: <%= ENV["CEPH_TOKEN"] %>
  ceph_key: <%= ENV["CEPH_KEY"] %>
  status_io_id: <%= ENV["STATUS_IO_ID"] %>
  status_io_key: <%= ENV["STATUS_IO_KEY"] %>
  status_io_page_id: <%= ENV["STATUS_IO_PAGE_ID"] %>
  stripe_webhook_secret: <%= ENV["STRIPE_WEBHOOK_SECRET"] %>

development:
  <<: *default
  secret_key_base: 5fcf63cf9eef04cf1c5ab2afcad3fa599893fabd34460b718c8252ee3620579076a89b81dbbd94720b61f0ad66a7c58dcf9d3fe528fd75d677be1663a3ac3aa2

test:
  <<: *default
  secret_key_base: 91fe5d494f16b1f3bff432c65d1b30a39e8881c0e842ab607f78f44260ea27f5da3b7c24b5347a57c3059858435b8fc6b2f918bc8fb516c34caecd7810aea7e0

acceptance:
  <<: *default
  secret_key_base: 91fe5d494f16b1f3bff432c65d1b30a39e8881c0e842ab607f78f44260ea27f5da3b7c24b5347a57c3059858435b8fc6b2f918bc8fb516c34caecd7810aea7e0

staging:
  <<: *default
  secret_key_base: a3b7c24b5347a57c3059858435b8fc6b2f918bc8fb516c34caecd7810aea7e091fe5d494f16b1f3bff432c65d1b30a39e8881c0e842ab607f78f44260ea27f5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
