default: &default
  domain: https://helpdesk.datacentred.io
  brand: DataCentred Staging

development:
  <<: *default

test:
  <<: *default

acceptance:
  <<: *default

staging:
  <<: *default

vagrant:
  <<: *default

production:
  <<: *default
  brand: DataCentred
