default: &default
  enabled: false
  notifications:
    new_signup:
      channel: '#signups'
      color: 'good'
      prefix: ':beers: Good news!'
    account_alert:
      channel: '#webdev'
      color: 'danger'
      prefix: ':crying_cat_face: Bad news!'
    internal_signup:
      channel: '#signups'
      color: 'good'
      prefix: ':beers: Good news!'
    new_user:
      channel: '#signups'
      color: 'good'
      prefix: ':key: Heads up!'
    sanity_check:
      channel: '#webdev'
      color: 'danger'
      prefix: ':crying_cat_face:'

development:
  <<: *default

test:
  <<: *default

acceptance:
  <<: *default

staging:
  <<: *default
  enabled: true

production:
  <<: *default
  enabled: true