default: &default
  enabled: false
  notifications:
    new_signup:
      channel: '#signups'
      color: 'good'
    account_alert:
      channel: '#webdev'
      color: 'danger'
    internal_signup:
      channel: '#signups'
      color: 'good'
    new_user:
      channel: '#signups'
      color: 'good'
    sanity_check:
      channel: '#webdev'
      color: 'danger'

development:
  <<: *default

test:
  <<: *default

acceptance:
  <<: *default

staging:
  <<: *default
  enabled: true

production:
  <<: *default
  enabled: true