default: &default
  enabled: false
  notifications:
    new_signup:
      channel: '#signups'
      color: 'good'
      prefix: ':beers: Good news!'
    account_alert:
      channel: '#webdev'
      color: 'danger'
      prefix: ':crying_cat_face: Bad news!'
    internal_signup:
      channel: '#signups'
      color: 'good'
      prefix: ':beers: Good news!'
    new_user:
      channel: '#signups'
      color: 'good'
      prefix: ':key: Heads up!'
    sanity_check:
      channel: '#webdev'
      color: 'danger'
      prefix: ':crying_cat_face:'
    code_quality_analysis:
      channel: '#webdev'
      color: 'warning'
      prefix: ':gem: Code Quality Results: '
    ssl_quality_check:
      channel: '#webdev'
      color: 'warning'
      prefix: ':lock: SSL Labs Quality Check: '
    test_coverage_percent:
      channel: '#webdev'
      color: 'warning'
      prefix: ':cloud: Test coverage: '
    security_analysis:
      channel: '#webdev'
      color: 'warning'
      prefix: ':lock: Security Analysis Results: '
    stripe_success:
      channel: '#billing'
      color: 'good'
      prefix: ':beers: Good news!'
    stripe_fail:
      channel: '#billing'
      color: 'warning'
      prefix: ':crying_cat_face: Uh oh:'
    good:
      channel: '#webdev'
      color: 'good'
      prefix: ':white_check_mark: Lovely: '

development:
  <<: *default

test:
  <<: *default
  enabled: true

acceptance:
  <<: *default

staging:
  <<: *default
  enabled: true

production:
  <<: *default
  enabled: true