default: &default
  standard:
    compute:
      instances: 5
      cores: 5
      ram: 10240
    volume:
      volumes: 4
      snapshots: 4
      gigabytes: 40
    network:
      floatingip: 1
      router: 1
      security_group_rule: 100
      security_group: 10
      network: 10
      port: 10
      subnet: 10
      pool: 10
      vip: 10

  restricted:
    compute:
      instances: 2
      cores: 2
      ram: 1024
    volume:
      volumes: 2
      snapshots: 2
      gigabytes: 20
    network:
      floatingip: 1
      router: 1
      security_group_rule: 100
      security_group: 10
      network: 10
      port: 10
      subnet: 10
      pool: 10
      vip: 10

  training:
    compute:
      instances: 6
      cores: 6
      ram: 6000
    volume:
      volumes: 6
      snapshots: 6
      gigabytes: 100
    network:
      floatingip: 2
      router: 1
      security_group_rule: 100
      security_group: 10
      network: 10
      port: 10
      subnet: 10
      pool: 10
      vip: 10

  zero:
    compute:
      instances: 0
      cores: 0
      ram: 0
      injected_file_content_bytes: 0
      injected_file_path_bytes: 0
      injected_files: 0
      key_pairs: 0
      metadata_items: 0
    volume:
      volumes: 0
      snapshots: 0
      gigabytes: 0
    network:
      floatingip: 0
      router: 0
      security_group_rule: 0
      security_group: 0
      network: 0
      port: 0
      subnet: 0
      pool: 0
      vip: 10

nolb: &nolb
  standard:
    compute:
      instances: 10
      cores: 10
      ram: 20480
    volume:
      volumes: 4
      snapshots: 4
      gigabytes: 40
    network:
      floatingip: 1
      router: 1
      security_group_rule: 100
      security_group: 10
      network: 10
      port: 10
      subnet: 10

  restricted:
    compute:
      instances: 2
      cores: 2
      ram: 1024
    volume:
      volumes: 2
      snapshots: 2
      gigabytes: 20
    network:
      floatingip: 1
      router: 1
      security_group_rule: 100
      security_group: 10
      network: 10
      port: 10
      subnet: 10

  training:
    compute:
      instances: 6
      cores: 6
      ram: 6000
    volume:
      volumes: 6
      snapshots: 6
      gigabytes: 100
    network:
      floatingip: 2
      router: 1
      security_group_rule: 100
      security_group: 10
      network: 10
      port: 10
      subnet: 10
      pool: 10
      vip: 10

  zero:
    compute:
      instances: 0
      cores: 0
      ram: 0
      injected_file_content_bytes: 0
      injected_file_path_bytes: 0
      injected_files: 0
      key_pairs: 0
      metadata_items: 0
    volume:
      volumes: 0
      snapshots: 0
      gigabytes: 0
    network:
      floatingip: 0
      router: 0
      security_group_rule: 0
      security_group: 0
      network: 0
      port: 0
      subnet: 0

development:
  <<: *nolb

test:
  <<: *nolb

staging:
  <<: *nolb

acceptance:
  <<: *nolb

production:
  <<: *default

