default: &default
  url: "https://private-anon-da34f38e6-statusio.apiary-proxy.com"

development:
  <<: *default

test:
  <<: *default

acceptance:
  <<: *default

staging:
  <<: *default

production:
  url: "https://api.status.io/v2/"
